language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeted

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  greeted;' -U postgres
  - psql -U postgres -d greeted-a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2